- name: Unpack the artifact
  become: yes
  unarchive:
    src: artifacts/artifact.tar.gz
    dest: /home/ubuntu
    remote_src: true

- name: Start app
  become: yes
  shell : |
    cd /home/ubuntu/
    npm install
    pm2 stop default
    pm2 start npm -- start