- name: "Backend app directory"
  file:
    path: ~/backend-app
    state: directory

- name: "Unpack the artifact"
  become: yes
  unarchive:
    src: "files/artifact.tar.gz"
    dest: .

#- name: "Install dependencies"
#  shell: |
#    cd ~/backend-app
#    npm install
#
#- name: "Execute app with pm2"
#  shell: |
#    cd ~/backend-app/dist
#    cd ../
#    npm install
#    npm run build
#    sudo npm install forever -g
#    sudo npm install ts-node -g
#    forever start -c "ts-node -r tsconfig-paths/register -r dotenv/config src/main.ts" ./
#  register: execute_node

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "Start app."
  become: yes
  shell : |
    npm install
    pm2 stop default
    pm2 start npm -- start